// engine/dom.js — Sélection des éléments du DOM (ui.*) et formatage d'affichage.
// Extrait d'app.js (même ordre de chargement, même espace global) : voir CLAUDE.md, « Moteur : engine/ ».
// ==========================================
// SÉLECTION DES ÉLÉMENTS DU DOM
// ==========================================
const ui = {
    playerName: document.getElementById('player-name'),
    floorLevel: document.getElementById('floor-level'),
    districtName: document.getElementById('district-name'),
    hpBar: document.getElementById('hp-bar'),
    hpText: document.getElementById('hp-text'),
    xpBarMini: document.getElementById('xp-bar-mini'),
    xpTextMini: document.getElementById('xp-text-mini'),
    bottomNav: document.getElementById('bottom-nav'),
    navEquipment: document.getElementById('nav-equipment'),
    navBag: document.getElementById('nav-bag'),
    navBagCount: document.getElementById('nav-bag-count'),
    navBagDot: document.getElementById('nav-bag-dot'),
    navSpellbook: document.getElementById('nav-spellbook'),
    navSpellbookDot: document.getElementById('nav-spellbook-dot'),
    equipmentSheet: document.getElementById('equipment-sheet'),
    bagSheet: document.getElementById('bag-sheet'),
    spellbookSheet: document.getElementById('spellbook-sheet'),
    equippedSpellSheet: document.getElementById('equipped-spell-sheet'),
    playerAtk: document.getElementById('player-atk'),
    playerDef: document.getElementById('player-def'),
    playerGold: document.getElementById('player-gold'),
    // Scène d'exploration (remplace l'ancienne carte à jouer, voir setSceneHeader()) : vignette,
    // emoji de repli, type, titre et dernière ligne du journal.
    exploreStage: document.getElementById('explore-stage'),
    exploreScene: document.getElementById('explore-scene'),
    sceneTypeLabel: document.getElementById('explore-type-label'),
    sceneIcon: document.getElementById('explore-icon'),
    sceneTitle: document.getElementById('explore-title'),
    sceneLastLine: document.getElementById('explore-last-line'),
    btnToggleMap: document.getElementById('btn-toggle-map'),
    screenFxOverlay: document.getElementById('screen-fx-overlay'),
    gameMain: document.getElementById('game-main'),
    fullLog: document.getElementById('full-log'),
    playerLevel: document.getElementById('player-level'),
    xpBar: document.getElementById('xp-bar'),
    xpText: document.getElementById('xp-text'),
    skillWeaponLevel: document.getElementById('skill-weapon-level'),
    skillWeaponBar: document.getElementById('skill-weapon-bar'),
    skillUnarmedLevel: document.getElementById('skill-unarmed-level'),
    skillUnarmedBar: document.getElementById('skill-unarmed-bar'),
    skillMagicLevel: document.getElementById('skill-magic-level'),
    skillMagicBar: document.getElementById('skill-magic-bar'),
    skillStealthLevel: document.getElementById('skill-stealth-level'),
    skillStealthBar: document.getElementById('skill-stealth-bar'),
    timeText: document.getElementById('time-text'),
    timeBar: document.getElementById('time-bar'),
    stairAlertBanner: document.getElementById('stair-alert-banner'),
    inventoryCount: document.getElementById('inventory-count'),
    consumableQuickbar: document.getElementById('consumable-quickbar'),
    inventoryEquipmentCards: document.getElementById('inventory-equipment-cards'),
    inventoryConsumablesIcons: document.getElementById('inventory-consumables-icons'),
    equippedWeapon: document.getElementById('equipped-weapon'),
    equippedArmor: document.getElementById('equipped-armor'),
    equippedArmorBadges: document.getElementById('equipped-armor-badges'),
    playerStatusIcons: document.getElementById('player-status-icons'),
    combatLastAction: document.getElementById('combat-last-action'),
    combatMobInfo: document.getElementById('combat-mob-info'),
    enemyStatusIcons: document.getElementById('enemy-status-icons'),
    combatEnemyDie: document.getElementById('combat-enemy-die'),
    combatPlayerStatus: document.getElementById('combat-player-status'),
    combatPlayerDie: document.getElementById('combat-player-die'),
    // Ancres des chiffres de dégâts flottants, placées sur chaque combattant par scene.js.
    sceneMobAnchor: document.getElementById('scene-mob-anchor'),
    sceneCrawlerAnchor: document.getElementById('scene-crawler-anchor'),
    advanceHint: document.getElementById('advance-hint'),
    bossChoiceZone: document.getElementById('boss-choice-zone'),
    stairsChoiceZone: document.getElementById('stairs-choice-zone'),
    btnDescendStairs: document.getElementById('btn-descend-stairs'),
    btnStayOnFloor: document.getElementById('btn-stay-on-floor'),
    btnFightBoss: document.getElementById('btn-fight-boss'),
    btnRetreatBoss: document.getElementById('btn-retreat-boss'),
    safehouseChoiceZone: document.getElementById('safehouse-choice-zone'),
    btnNapSafehouse: document.getElementById('btn-nap-safehouse'),
    btnSleepSafehouse: document.getElementById('btn-sleep-safehouse'),
    btnLeaveSafehouse: document.getElementById('btn-leave-safehouse'),
    stealthChoiceZone: document.getElementById('stealth-choice-zone'),
    btnStealthEvade: document.getElementById('btn-stealth-evade'),
    btnStealthAttack: document.getElementById('btn-stealth-attack'),
    gameOverOverlay: document.getElementById('game-over-overlay'),
    gameOverReason: document.getElementById('game-over-reason'),
    gameOverFloor: document.getElementById('game-over-floor'),
    gameOverLevel: document.getElementById('game-over-level'),
    gameOverDistrict: document.getElementById('game-over-district'),
    gameOverEpitaph: document.getElementById('game-over-epitaph'),
    gameOverAchievements: document.getElementById('game-over-achievements'),
    winAchievements: document.getElementById('win-achievements'),
    achievementToast: document.getElementById('achievement-toast'),
    bountyStatus: document.getElementById('bounty-status'),
    showZone: document.getElementById('show-zone'),
    minigameStrip: document.getElementById('minigame-strip'),
    minigameTitle: document.getElementById('minigame-title'),
    minigameHint: document.getElementById('minigame-hint'),
    minigameTimerBar: document.getElementById('minigame-timer-bar'),
    minigameBody: document.getElementById('minigame-body'),
    minigameSkip: document.getElementById('minigame-skip'),
    minigameBanner: document.getElementById('minigame-banner'),
    minigameModeSelect: document.getElementById('minigame-mode-select'),
    btnDevMinigame: document.getElementById('btn-dev-minigame'),
    showHost: document.getElementById('show-host'),
    showTaunt: document.getElementById('show-taunt'),
    showPopularity: document.getElementById('show-popularity'),
    showButtons: {
        polite: document.getElementById('btn-show-polite'),
        retort: document.getElementById('btn-show-retort'),
        provoke: document.getElementById('btn-show-provoke'),
        insult: document.getElementById('btn-show-insult')
    },
    btnShowRefuse: document.getElementById('btn-show-refuse'),
    achievementsCount: document.getElementById('achievements-count'),
    btnAchievements: document.getElementById('btn-achievements'),
    achievementsOverlay: document.getElementById('achievements-overlay'),
    achievementsList: document.getElementById('achievements-list'),
    achievementsTitleCount: document.getElementById('achievements-title-count'),
    btnCloseAchievements: document.getElementById('btn-close-achievements'),
    btnRestart: document.getElementById('btn-restart'),
    winOverlay: document.getElementById('win-overlay'),
    winFloor: document.getElementById('win-floor'),
    winLevel: document.getElementById('win-level'),
    btnWinRestart: document.getElementById('btn-win-restart'),
    floorTransitionOverlay: document.getElementById('floor-transition-overlay'),
    floorTransitionTitle: document.getElementById('floor-transition-title'),
    floorTransitionMobs: document.getElementById('floor-transition-mobs'),
    floorTransitionDamage: document.getElementById('floor-transition-damage'),
    floorTransitionItems: document.getElementById('floor-transition-items'),
    floorTransitionXp: document.getElementById('floor-transition-xp'),
    floorTransitionAnomaly: document.getElementById('floor-transition-anomaly'),
    floorTransitionAnomalyText: document.getElementById('floor-transition-anomaly-text'),
    btnFloorTransitionContinue: document.getElementById('btn-floor-transition-continue'),
    anomalyStatusBar: document.getElementById('anomaly-status-bar'),
    starterBuffStatus: document.getElementById('starter-buff-status'),
    trialStatus: document.getElementById('trial-status'),
    raceStatus: document.getElementById('race-status'),
    classStatus: document.getElementById('class-status'),
    raceChoiceOverlay: document.getElementById('race-choice-overlay'),
    classChoiceOverlay: document.getElementById('class-choice-overlay'),
    raceChoiceCards: document.getElementById('race-choice-cards'),
    classChoiceCards: document.getElementById('class-choice-cards'),
    btnRaceConfirm: document.getElementById('btn-race-confirm'),
    btnClassConfirm: document.getElementById('btn-class-confirm'),
    pactChoiceOverlay: document.getElementById('pact-choice-overlay'),
    btnPactAtk: document.getElementById('btn-pact-atk'),
    btnPactHp: document.getElementById('btn-pact-hp'),
    combatZone: document.getElementById('combat-zone'),
    floorMapOverlay: document.getElementById('floor-map-overlay'),
    floorMapSvg: document.getElementById('floor-map-svg'),
    floorMapLegend: document.getElementById('floor-map-legend'),
    floorMapBubble: document.getElementById('floor-map-bubble'),
    floorMapBubbleTitle: document.getElementById('floor-map-bubble-title'),
    floorMapBubbleText: document.getElementById('floor-map-bubble-text'),
    btnFloorMapGo: document.getElementById('btn-floor-map-go'),
    btnFloorMapCancel: document.getElementById('btn-floor-map-cancel'),
    btnFloorMapZoomIn: document.getElementById('btn-floor-map-zoom-in'),
    btnFloorMapZoomOut: document.getElementById('btn-floor-map-zoom-out'),
    btnFloorMapRecenter: document.getElementById('btn-floor-map-recenter'),
    companionChoiceFriendly: document.getElementById('companion-choice-friendly'),
    companionChoiceHostile: document.getElementById('companion-choice-hostile'),
    btnRecruitFriendly: document.getElementById('btn-recruit-friendly'),
    btnDeclineCompanion: document.getElementById('btn-decline-companion'),
    btnFleeCompanion: document.getElementById('btn-flee-companion'),
    btnRecruitHostile: document.getElementById('btn-recruit-hostile'),
    btnAttackCompanion: document.getElementById('btn-attack-companion'),
    shopZone: document.getElementById('shop-zone'),
    shopMerchantContent: document.getElementById('shop-merchant-content'),
    shopTrainerContent: document.getElementById('shop-trainer-content'),
    shopStockList: document.getElementById('shop-stock-list'),
    shopSellList: document.getElementById('shop-sell-list'),
    shopSellSpellsList: document.getElementById('shop-sell-spells-list'),
    shopTrainerInfo: document.getElementById('shop-trainer-info'),
    btnTrainSkill: document.getElementById('btn-train-skill'),
    btnLeaveShop: document.getElementById('btn-leave-shop'),
    shopArcadeContent: document.getElementById('shop-arcade-content'),
    arcadeStake: document.getElementById('arcade-stake'),
    arcadeStakeInfo: document.getElementById('arcade-stake-info'),
    arcadeGames: document.getElementById('arcade-games'),
    arcadeRounds: document.getElementById('arcade-rounds'),
    arcadeMessage: document.getElementById('arcade-message'),
    lairChoiceZone: document.getElementById('lair-choice-zone'),
    btnDiveLair: document.getElementById('btn-dive-lair'),
    btnDeclineLair: document.getElementById('btn-decline-lair'),
    companionStatusBar: document.getElementById('companion-status-bar'),
    companionNameDisplay: document.getElementById('companion-name-display'),
    companionSpecialtyDisplay: document.getElementById('companion-specialty-display'),
    companionLoyaltyBar: document.getElementById('companion-loyalty-bar'),
    companionHpDisplay: document.getElementById('companion-hp-display'),
    companionInfoFriendly: document.getElementById('companion-info-friendly'),
    companionInfoHostile: document.getElementById('companion-info-hostile'),
    companionCombatIndicator: document.getElementById('companion-combat-indicator'),
    companionCombatName: document.getElementById('companion-combat-name'),
    companionCombatHpRing: document.getElementById('companion-combat-hp-ring'),
    companionCombatHp: document.getElementById('companion-combat-hp'),
    enemyName: document.getElementById('enemy-name'),
    telegraphBanner: document.getElementById('telegraph-banner'),
    phaseTransitionBanner: document.getElementById('phase-transition-banner'),
    bossPhaseBadge: document.getElementById('boss-phase-badge'),
    btnAttackWeapon: document.getElementById('btn-attack-weapon'),
    btnAttackRanged: document.getElementById('btn-attack-ranged'),
    btnAttackUnarmed: document.getElementById('btn-attack-unarmed'),
    btnAttackMagic: document.getElementById('btn-attack-magic'),
    btnSprint: document.getElementById('btn-sprint'),
    btnRetreat: document.getElementById('btn-retreat'),
    btnEngage: document.getElementById('btn-engage'),
    btnOccasion: document.getElementById('btn-occasion'),
    btnClassAbility: document.getElementById('btn-class-ability'),
    finisherCinema: document.getElementById('finisher-cinema'),
    finisherCinemaText: document.getElementById('finisher-cinema-text'),
    btnFlee: document.getElementById('btn-flee'),
    distanceTensionLabel: document.getElementById('distance-tension-label'),
    equippedRanged: document.getElementById('equipped-ranged'),
    btnDevTestKit: document.getElementById('btn-dev-testkit'),
    btnDevJumpUrban: document.getElementById('btn-dev-jump-urban'),
    equippedSpell: document.getElementById('equipped-spell'),
    spellbookCards: document.getElementById('spellbook-cards'),
    manaBarWrapper: document.getElementById('mana-bar-wrapper'),
    manaText: document.getElementById('mana-text'),
    manaBar: document.getElementById('mana-bar'),
    combatManaWrapper: document.getElementById('combat-mana-wrapper'),
    combatManaText: document.getElementById('combat-mana-text'),
    combatManaBar: document.getElementById('combat-mana-bar'),
    startScreenOverlay: document.getElementById('start-screen-overlay'),
    startNameInput: document.getElementById('start-name-input'),
    startSavesHint: document.getElementById('start-saves-hint'),
    versionLabel: document.getElementById('version-label'),
    btnStartConfirm: document.getElementById('btn-start-confirm'),
    btnOpenManageSaves: document.getElementById('btn-open-manage-saves'),
    manageSavesOverlay: document.getElementById('manage-saves-overlay'),
    manageSavesList: document.getElementById('manage-saves-list'),
    manageSavesConfirm: document.getElementById('manage-saves-confirm'),
    manageSavesConfirmText: document.getElementById('manage-saves-confirm-text'),
    btnManageSavesConfirmYes: document.getElementById('btn-manage-saves-confirm-yes'),
    btnManageSavesConfirmNo: document.getElementById('btn-manage-saves-confirm-no'),
    btnManageSavesDeleteAll: document.getElementById('btn-manage-saves-delete-all'),
    btnManageSavesRestoreBackup: document.getElementById('btn-manage-saves-restore-backup'),
    btnManageSavesClose: document.getElementById('btn-manage-saves-close'),
    giftRevealOverlay: document.getElementById('gift-reveal-overlay'),
    giftRevealIcon: document.getElementById('gift-reveal-icon'),
    giftRevealTitle: document.getElementById('gift-reveal-title'),
    giftRevealItemName: document.getElementById('gift-reveal-item-name'),
    giftRevealJoke: document.getElementById('gift-reveal-joke'),
    btnGiftContinue: document.getElementById('btn-gift-continue'),
    // Inspection d'un objet (voir openItemInspect())
    itemInspectOverlay: document.getElementById('item-inspect-overlay'),
    itemInspectPanel: document.getElementById('item-inspect-panel'),
    itemInspectBody: document.getElementById('item-inspect-body'),
    itemInspectActions: document.getElementById('item-inspect-actions'),
    inventoryMax: document.getElementById('inventory-max')
};

// ==========================================
// 5. AFFICHAGE ET MISE À JOUR DE L'UI
// ==========================================
// Formate un nombre d'heures restantes en "Xj Yh" (ou juste "Yh" si moins d'un jour plein),
// pour rester lisible sur le badge compact une fois le temps alloué augmenté au-delà de 24H.
function formatTimeRemaining(hours) {
    const total = Math.max(0, Math.round(hours));
    const days = Math.floor(total / 24);
    const rem = total % 24;
    return days > 0 ? `${days}j ${rem}h` : `${rem}h`;
}

// Empile sur l'overlay d'ambiance les classes correspondant aux états critiques actuellement actifs
// (PV bas, saignement/brûlure, confusion, aveuglement, corrosion, peur) : plusieurs peuvent être
// visibles à la fois. Appelé à chaque updateUI(), aussi bien en combat que hors combat (un
// saignement ou une confusion peuvent survivre un instant après un combat interrompu par une fuite).
function applyScreenStateEffects() {
    if (!ui.screenFxOverlay) return;
    const classes = {
        'fx-low-hp': gameState.maxHp > 0 && (gameState.hp / gameState.maxHp) <= 0.25 && gameState.hp > 0,
        'fx-burn': !!(gameState.status.bleed && gameState.status.bleed.rounds > 0),
        'fx-confused': !!(gameState.status.confused && gameState.status.confused.rounds > 0),
        'fx-blinded': !!(gameState.status.blinded && gameState.status.blinded.rounds > 0),
        'fx-corroded': !!(gameState.status.corroded && gameState.status.corroded.rounds > 0),
        'fx-feared': !!(gameState.status.feared && gameState.status.feared.rounds > 0)
    };
    for (const cls in classes) {
        ui.screenFxOverlay.classList.toggle(cls, classes[cls]);
    }
}
